# Generated by Django 4.2.4 on 2023-11-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0004_remove_contact_latitude_remove_contact_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=35.0298, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=87.0031, max_digits=9),
            preserve_default=False,
        ),
    ]
